import { UserDrawer } from '@/components/drawers/UserDrawer';
import { Button } from '@/components/ui/buttons/Button';
import { useToggle } from '@/hooks/util/useToggle';
import Head from 'next/head';

const Home = () => {
	const { state, toggleHandler } = useToggle(false, 350);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Button onClick={toggleHandler}>CLICK</Button>
				<UserDrawer isShow={state} toggleShow={toggleHandler} />
			</main>
		</>
	);
};

export default Home;
