import Head from 'next/head';

import { UserDrawer } from '@/entities/User';

import { useToggle } from '@/shared/hooks';
import { Button } from '@/shared/ui/Button';

const Home = () => {
	const { state, toggleHandler } = useToggle(false, 350);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<UserDrawer isShow={state} closeHandler={toggleHandler} />
				<Button onClick={toggleHandler}>CLICK</Button>
			</main>
		</>
	);
};

export default Home;
